"""empty message

Revision ID: 1fee2d9b528c
Revises: 
Create Date: 2025-05-16 10:40:25.517162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fee2d9b528c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False, comment='Код пункта'),
    sa.Column('description', sa.String(length=250), nullable=False, comment='Название пункта'),
    sa.Column('image_url', sa.String(length=250), nullable=True),
    sa.Column('page_url', sa.String(length=250), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_modal', sa.Boolean(), nullable=False, comment='Признак модального окна'),
    sa.Column('modal_text', sa.String(), nullable=True, comment='Текст для модального окна'),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Дата и время обновления записи'),
    sa.ForeignKeyConstraint(['parent_id'], ['help_menu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('help_section',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=True, comment='Код'),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('page_url', sa.String(length=250), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Время удаления'),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Дата и время обновления записи'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('help_widget',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('help_subsection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True, comment='Код'),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('document_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Время удаления'),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Дата и время обновления записи'),
    sa.ForeignKeyConstraint(['section_id'], ['help_section.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('help_articlecontent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subsection_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('subtitle', sa.String(length=100), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('image_id', sa.Uuid(), nullable=True),
    sa.Column('widget_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Дата и время обновления записи'),
    sa.ForeignKeyConstraint(['subsection_id'], ['help_subsection.id'], ),
    sa.ForeignKeyConstraint(['widget_id'], ['help_widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('help_subsectiondocument',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subsection_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Время удаления'),
    sa.ForeignKeyConstraint(['subsection_id'], ['help_subsection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('help_subsectiondocument')
    op.drop_table('help_articlecontent')
    op.drop_table('help_subsection')
    op.drop_table('help_widget')
    op.drop_table('help_section')
    op.drop_table('help_menu')
    # ### end Alembic commands ###
